/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Accesso: typeof import('./src/components/Accesso.vue')['default']
    Aggiungi: typeof import('./src/components/mete__log/Aggiungi.vue')['default']
    Artista: typeof import('./src/components/artista.vue')['default']
    Benvenuto: typeof import('./src/components/Benvenuto.vue')['default']
    Cerca: typeof import('./src/components/mete__log/Cerca.vue')['default']
    Esplora: typeof import('./src/components/mete__log/Esplora.vue')['default']
    Home: typeof import('./src/components/home.vue')['default']
    ModifyPost: typeof import('./src/components/mete__log/modifyPost.vue')['default']
    Modifyprofile: typeof import('./src/components/modifyprofile.vue')['default']
    ModifyProfilo: typeof import('./src/components/mete__log/modifyProfilo.vue')['default']
    Opera: typeof import('./src/components/opera.vue')['default']
    Post: typeof import('./src/components/mete__log/post.vue')['default']
    Profilo: typeof import('./src/components/profilo.vue')['default']
    Ricerca: typeof import('./src/components/ricerca.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Voli: typeof import('./src/components/mete__log/Voli.vue')['default']
  }
}
